---
- name: Run K3s Install for agents
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_SKIP_DOWNLOAD: "true"
  changed_when: true

- name: Make config directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s"
    mode: 0755
    state: directory

- name: Copy config values
  ansible.builtin.copy:
    src: config.yaml
    dest: "/etc/rancher/k3s/config.yaml"
    mode: 0644

- name: Copy K3s service file
  register: k3s_server_service
  ansible.builtin.template:
    src: "k3s-server.service.j2"
    dest: "{{ systemd_dir }}/k3s-server.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-server
    daemon_reload: "{{ true if k3s_server_service.changed else false }}"
    state: "{{ 'restarted' if k3s_server_service.changed else 'started' }}"
    enabled: true
