k3s_cluster:
  children:
    server:
      hosts:
        192.168.122.100:
    agent:
      hosts:
        192.168.122.101:
        192.168.122.102:

  vars:
    k3s_data_dir: /var/lib/rancher/k3s
    systemd_dir : /etc/systemd/system
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    api_port : 6443
    token: testtoken