---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Make images directory
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/agent/images/"
    mode: 0755
    state: directory

- name: Distribute K3s amd64 images
  ansible.builtin.copy:
    src: "{{ airgap_dir }}/k3s-airgap-images-amd64.tar.gz"
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.gz
    owner: root
    group: root
    mode: 0755

- name: Distribute K3s binary
  ansible.builtin.copy:
    src: "{{ airgap_dir }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755


- name: Copy K3s install script
  ansible.builtin.copy:
    src: k3s-install.sh
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755